project:
  type: book
  output-dir: docs

author-title: "Autores"
published-title: "Data"
book:
  title: "Modelos Lineares I - Seminário"
  author: 
    - name: "Gustavo Jun Yakushiji"
    - name: "Luís Bernardo Patrício"
  date: 04/01/2024
  date-format: "DD/MMMM/YYYY"
  
  site-url: https://github.com/gustavojy/mod-lin-r
  repo-url: https://github.com/gustavojy/mod-lin-r
  repo-branch: main

  chapters:
    - index.qmd
    
    - part: "Covariância, Correlação e Distância de Mahalanobis"
      chapters: 
        - exemplo1.qmd
    
    - part: "Distribuição Normal Multivariada"
      chapters:
        - exemplo2.1.qmd
        - exemplo2.2.qmd
        - exemplo2.3.qmd

    - part: "Regressão Linear Simples"
      chapters:
        - exemplo3.1.qmd

    - part: "Regressão Linear Múltipla"
      chapters:
        - exemplo4.1.qmd
        - exemplo4.2.qmd
        - exemplo4.3.qmd
        - exemplo4.4.qmd
        - exemplo4.5.qmd

    - part: "Modelos de Análise de Variância (ANOVA)"
      chapters:
        - exemplo5.1.qmd
        - exemplo5.2.qmd
        - exemplo5.3.qmd
        # - exemplo5.4.qmd
        # - exemplo5.5.qmd
        # - exemplo5.6.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-link: true

lang: pt-BR